(function() {var implementors = {};
implementors["walrus"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/hash/trait.Hash.html\" title=\"trait core::hash::Hash\">Hash</a> for <a class=\"struct\" href=\"walrus/ir/struct.Local.html\" title=\"struct walrus::ir::Local\">Local</a>",synthetic:false,types:["walrus::ir::Local"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/hash/trait.Hash.html\" title=\"trait core::hash::Hash\">Hash</a> for <a class=\"struct\" href=\"walrus/struct.UntypedCustomSectionId.html\" title=\"struct walrus::UntypedCustomSectionId\">UntypedCustomSectionId</a>",synthetic:false,types:["walrus::module::custom::UntypedCustomSectionId"]},{text:"impl&lt;T&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/hash/trait.Hash.html\" title=\"trait core::hash::Hash\">Hash</a> for <a class=\"struct\" href=\"walrus/struct.TypedCustomSectionId.html\" title=\"struct walrus::TypedCustomSectionId\">TypedCustomSectionId</a>&lt;T&gt; <span class=\"where fmt-newline\">where<br>&nbsp;&nbsp;&nbsp;&nbsp;T: <a class=\"trait\" href=\"walrus/trait.CustomSection.html\" title=\"trait walrus::CustomSection\">CustomSection</a>,&nbsp;</span>",synthetic:false,types:["walrus::module::custom::TypedCustomSectionId"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/hash/trait.Hash.html\" title=\"trait core::hash::Hash\">Hash</a> for <a class=\"struct\" href=\"walrus/struct.Import.html\" title=\"struct walrus::Import\">Import</a>",synthetic:false,types:["walrus::module::imports::Import"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/hash/trait.Hash.html\" title=\"trait core::hash::Hash\">Hash</a> for <a class=\"enum\" href=\"walrus/enum.ImportKind.html\" title=\"enum walrus::ImportKind\">ImportKind</a>",synthetic:false,types:["walrus::module::imports::ImportKind"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/hash/trait.Hash.html\" title=\"trait core::hash::Hash\">Hash</a> for <a class=\"struct\" href=\"walrus/struct.Type.html\" title=\"struct walrus::Type\">Type</a>",synthetic:false,types:["walrus::ty::Type"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/hash/trait.Hash.html\" title=\"trait core::hash::Hash\">Hash</a> for <a class=\"enum\" href=\"walrus/enum.ValType.html\" title=\"enum walrus::ValType\">ValType</a>",synthetic:false,types:["walrus::ty::ValType"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
